replicaCount: 1

image:
  repository: registry.kube-system.svc.cluster.local:5000/deeptrust-app
  tag: canary-1.0.0

service:
  port: 8080
  externalIP: ""   # Placeholder

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"


fastapi:
  externalIP: ""  
  port: 8200  

triton:
  port: 8210

vllm:
  port: 8205   
