---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-studio
  namespace: deeptrust-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-studio
  template:
    metadata:
      labels:
        app: label-studio
    spec:
      containers:
        - name: label-studio
          image: :heartexlabs/label-studio:1.16.0
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "labelstudiodb"
            - name: POSTGRES_HOST
              value: "app-db"
            - name: LABEL_STUDIO_URL
              value: "http://label-studio:8080"
            - name: LABEL_STUDIO_USERNAME
              value: "labelstudio@example.com"
            - name: LABEL_STUDIO_PASSWORD
              value: "labelstudio"
            - name: LABEL_STUDIO_USER_TOKEN
              value: "ab9927067c51ff279d340d7321e4890dc2841c4a"
            - name: MINIO_URL
              value: "http://minio:9000"  
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: accesskey
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secretkey  
              ports:
                - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: label-studio
  namespace: deeptrust-platform
spec:
  selector:
    app: label-studio
  ports:
    - port: 8080
      targetPort: 8080