---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: deeptrust-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: registry.kube-system.svc.cluster.local:5000/prometheus-deeptrust:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: deeptrust-platform
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  externalIPs:
    - {{ .Values.prometheus.externalIP }}  
  