global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'deeptrust'
    static_configs:
      - targets: ['129.114.109.86:8200','129.114.109.86:8202'] 
      
  - job_name: vllm
    static_configs:
      - targets:
          - '129.114.109.86:8206'

# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: 'deeptrust'
#     static_configs:
#       - targets: ['fastapi_server:8000','triton_server:8002'] 
      
#   - job_name: vllm
#     static_configs:
#       - targets:
#           - '192.5.86.181:8005'