{
 "title": "DeepTrust Service Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "FastAPI (ViT) - Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/predict\"}[1m])",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "FastAPI (ViT) - Requests that return Error/Failed Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/predict\", status=\"4xx\"}[1m])",
     "legendFormat": "Requests that have 4xx error on client side"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/predict\", status=\"5xx\"}[1m])",
     "legendFormat": "Requests that have 5xx error on server side"
    }
   ]
  },
  {
   "title": "Fast API (ViT) - request duration percentiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "1000*histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler=\"/predict\"}[1m]))",
     "legendFormat": "Median"
    },
    {
     "expr": "1000*histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler=\"/predict\"}[1m]))",
     "legendFormat": "95 Percentile"
    },
    {
     "expr": "1000*histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{handler=\"/predict\"}[1m]))",
     "legendFormat": "99 Percentile"
    }
   ]
  },
  {
   "title": "FastAPI (ViT) - Avg request duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "1000 * rate(http_request_duration_seconds_sum{handler=\"/predict\", job=\"deeptrust\"}[1m]) / \nrate(http_request_duration_seconds_count{handler=\"/predict\", job=\"deeptrust\"}[1m])",
     "legendFormat": "Avg Request Duration (ms)"
    }
   ]
  },
  {
   "title": "Triton (BLIP) - Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(nv_inference_count[1m])",
     "legendFormat": "number of inferences in a minute"
    }
   ]
  },
  {
   "title": "Triton - Avg GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 13 },
   "targets": [
    { "expr": "avg(nv_gpu_utilization)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Triton (BLIP) - Inference Latency (us)",
   "type": "timeseries",
   "description": "Time (in microseconds) it takes to process a single inference request",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "avg(rate(nv_inference_request_duration_us[1m])) / 1000",
     "legendFormat": "Inference latency in microseconds"
    }
   ]
  }
 ]
}