{
 "title": "DeepTrust Service Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/predict\"}[1m])",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "DeepTrust average request duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "1000 * rate(http_request_duration_seconds_sum{handler=\"/predict\", job=\"deeptrust\"}[1m]) / \nrate(http_request_duration_seconds_count{handler=\"/predict\", job=\"deeptrust\"}[1m])",
     "legendFormat": "Avg Request Duration (ms)"
    }
   ]
  },
  {
   "title": "DeepTrust request duration percentiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "1000*histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler=\"/predict\"}[1m]))",
     "legendFormat": "Median"
    },
    {
     "expr": "1000*histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler=\"/predict\"}[1m]))",
     "legendFormat": "95 Percentile"
    },
    {
     "expr": "1000*histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{handler=\"/predict\"}[1m]))",
     "legendFormat": "99 Percentile"
    }
   ]
  },
  {
   "title": "Requests that return Error/Failed Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/predict\", status=\"4xx\"}[1m])",
     "legendFormat": "Requests that have 4xx error on client side"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/predict\", status=\"5xx\"}[1m])",
     "legendFormat": "Requests that have 5xx error on server side"
    }
   ]
  }
 ]
}