# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeptrust-app
  namespace: deeptrust-production
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: deeptrust-app
  template:
    metadata:
      labels:
        app: deeptrust-app
    spec:
      containers:
        - name: deeptrust-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 5000
          env:
            - name: FASTAPI_SERVER_URL
              value: "http://{{.Values.fastapi.externalIP}}:{{.Values.fastapi.port}}"
            - name: MINIO_URL
              value: "http://minio:9000"
            - name: MINIO_USER
              value: "your-access-key"
            - name: MINIO_PASSWORD
              value: "your-secret-key"    
            - name: TRITON_SERVER_URL
              value: "{{.Values.fastapi.externalIP}}:{{.Values.triton.port}}"
            - name: VLLM_SERVER_URL
              value: "http://{{.Values.fastapi.externalIP}}:{{.Values.vllm.port}}/v1/completions"  
             
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: deeptrust-app
  namespace: deeptrust-production
spec:
  selector:
    app: deeptrust-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  externalIPs:
    - {{ .Values.service.externalIP }}
