# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeptrust-app
  namespace: deeptrust-production
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: deeptrust-app
  template:
    metadata:
      labels:
        app: deeptrust-app
    spec:
      containers:
        - name: deeptrust-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 5000
          env:
            - name: FASTAPI_SERVER_URL
              value: "http://{{.Values.fastapi.externalIP}}:{{.Values.fastapi.port}}"
            - name: VLLM_SERVER_URL
              value: "http://{{.Values.fastapi.externalIP}}:{{.Values.vllm.port}}/v1/completions"    
            - name: TRITON_SERVER_URL
              value: "{{.Values.fastapi.externalIP}}:{{.Values.triton.port}}"
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: accesskey
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secretkey    
            - name: MINIO_URL
              value: "http://{{.Values.kvm.externalIP}}"
             
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: deeptrust-app
  namespace: deeptrust-production
spec:
  selector:
    app: deeptrust-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  externalIPs:
    - {{ .Values.service.externalIP }}
