name: triton_test
services:
  triton_server:
    build:
      context: /home/cc/work/BLIP
      dockerfile: Dockerfile.triton
    container_name: triton_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"  # for HTTP requests
      - "8001:8001"  # for GRPC requests
      - "8002:8002"  # for reporting metrics

  jupyter:
    image: quay.io/jupyter/minimal-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - /home/cc/work:/home/jovyan/work # mount workspace
    command: >
      bash -c "python3 -m pip install bash_kernel tritonclient[all] && 
               python3 -m bash_kernel.install && start-notebook.sh"
