---
- name: Set up from GitHub Repo
  hosts: node1
  become: yes
  vars:
    repo_url: "https://github.com/SimranKucheria/ECE-GY-9183-Machine-Learning-Systems-Engg-Operations-Project.git"
    repo_dest: /tmp/deeptrust

  tasks:
    - name: Clone or update deeptrust repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main   

- name: Set up from GitHub Repo
  hosts: node1
  become: yes
  vars:
    repo_url: "https://github.com/SimranKucheria/ECE-GY-9183-Machine-Learning-Systems-Engg-Operations-Project.git"
    repo_dest: /tmp/deeptrust
   

  tasks:
    - name: Clone or update deeptrust repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main                          
    - name: Run Online testing for 1st model
      shell: |
        docker compose -f /tmp/deeptrust/src/data-persist/docker-environments/docker-online-data-simulator_regnet.yaml up -d    
      environment:
            FLOATING_IP: "A.B.C.D"
    - name: Run Online testing for 2nd model
      shell: |
        docker compose -f /tmp/deeptrust/src/data-persist/docker-environments/docker-online-data-simulator_blip.yaml up -d    
      environment:
            FLOATING_IP: "A.B.C.D" 
    - name: Run Online testing for 3rd model
      shell: |
        docker compose -f /tmp/deeptrust/src/data-persist/docker-environments/docker-online-data-vllm.yaml up -d    
      environment:
            FLOATING_IP: "A.B.C.D"                    