---
- name: Configure RClone Confs
  hosts: node1
  become: yes
  tasks:
    - name: Install Rclone
      shell: |
        curl https://rclone.org/install.sh | sudo bash
    - name: Ensure RClone availability to other docker containers
      shell: |
        sudo sed -i '/^#user_allow_other/s/^#//' /etc/fuse.conf  
    - name: Create RClone configs
      shell: |
        mkdir -p ~/.config/rclone     
    - name: Change RClone confs I
      shell: |
        sed -i 's/'"YOUR_USER_ID"'/'<INSERTUSERID>'/g' /tmp/deeptrust/src/data-persist/rclone.conf
    - name: Change RClone confs II
      shell: |
        sed -i 's/'"APP_CRED_ID"'/'"<INSERTAPPCRED>"'/g' /tmp/deeptrust/src/data-persist/rclone.conf
    - name: Change RClone confs III
      shell: |
        sed -i 's/'"APP_CRED_SECRET"'/'<INSERTAPPCREDSEC>'/g' /tmp/deeptrust/src/data-persist/rclone.conf   
    
    - name: Copy a RClone confs file on the remote machine for editing
      ansible.builtin.copy:
        src: /tmp/deeptrust/src/data-persist/rclone.conf
        dest: /home/cc/.config/rclone/
        remote_src: yes                               

- name: LoadData into Object Storage
  hosts: node1
  become: yes
  tasks:
    - name: Run Extract Data Stage For Regnet
      shell: |
        docker compose -f /tmp/deeptrust/src/data-persist/docker-regnet-data-persist.yaml run extract-data  
    - name: Run Sanitise Data Stage For Regnet
      shell: |
        docker compose -f /tmp/deeptrust/src/data-persist/docker-regnet-data-persist.yaml run sanitise-data  
    - name: Run Transform Data Stage For Regnet
      shell: |
        docker compose -f /tmp/deeptrust/src/data-persist/docker-regnet-data-persist.yaml run transform-data 
    - name: Run Extract Data Stage For Blip
      shell: |
        docker compose -f /tmp/deeptrust/src/data-persist/docker-blip-data-persist.yaml run extract-data  
    - name: Run Sanitise Data Stage For Blip
      shell: |
        docker compose -f /tmp/deeptrust/src/data-persist/docker-blip-data-persist.yaml run sanitise-data  
    - name: Run Transform Data Stage For Blip
      shell: |
        docker compose -f /tmp/deeptrust/src/data-persist/docker-blip-data-persist.yaml run tranform-data  
    - name: Run Load Data Stage For Regnet and Blip
      shell: |
        docker compose -f /tmp/deeptrust/src/data-persist/docker-load-data-persist.yaml run load-data  
      environment:
            RCLONE_CONTAINER: object-persist-project3           