name: online-data-simulator
services:
    online_data_simulator:
      container_name: online_data_simulator_regnet
      image: python:3.11
      volumes:
        - /mnt/object/AiVsHuman:/data/AiVsHuman
        - /tmp/deeptrust/src/data-persist/:/data/scripts
      environment:
        - FASTAPI_URL=http://${FLOATING_IP}:8200/predict
        - LOAD_PATTERN=1,2,3,5,3,2,1
        - DELAY_BETWEEN_STEPS=60
        - REQUEST_TIMEOUT=5
      command:
        - bash
        - -c
        - |
          pip install requests pillow pandas
          python /data/scripts/online_data_simulator_regnet.py