name: online-data-simulator
services:
  online_data_simulator:
    container_name: online_data_simulator_vllm
  image: python:3.11
  volumes:
    - /mnt/object/Flickr30k:/data/Flickr30k
    - /tmp/deeptrust/src/data-persist/:/data/scripts
  environment:
    - VLLM_SERVER_URL=http://${FLOATING_IP}:8205/v1/completions
    - LOAD_PATTERN=1,2,3,5,3,2,1
    - DELAY_BETWEEN_STEPS=60
    - REQUEST_TIMEOUT=5
  command:
    - bash
    - -c
    - |
      set -e
      pip install requests
      echo "Running vLLM online data simulator..."
      python3 /data/scripts/online_data_simulator_vllm.py
