name: online-data-simulator
services:
  online_data_simulator:
    container_name: online_data_simulator_blip
    image: python:3.11
    volumes:
      - /mnt/object/Flickr30k:/data/Flickr30k
      - /tmp/deeptrust/src/data-persist/:/data/scripts
    environment:
      - TRITON_SERVER_URL=${FLOATING_IP}:8210
      - LOAD_PATTERN=1,2,3,5,3,2,1
      - DELAY_BETWEEN_STEPS=60
      - REQUEST_TIMEOUT=5
      - USE_TRITON=true
    command:
      - bash
      - -c
      - |
        pip install requests pillow numpy tritonclient[http]
        python /data/scripts/online_data_simulator_blip.py
